import 'package:hive/hive.dart';

part 'expense_model.g.dart'; // This file will be generated by build_runner

@HiveType(typeId: 0)
class Expense extends HiveObject {
  @HiveField(0)
  final String id;
  @HiveField(1)
  final String userId;
  @HiveField(2)
  final String category;
  @HiveField(3)
  final String description;
  @HiveField(4)
  final double amount;
  @HiveField(5)
  final DateTime date;
  @HiveField(6)
  final String vendor;

  Expense({
    required this.id,
    required this.userId,
    required this.category,
    required this.description,
    required this.amount,
    required this.date,
    required this.vendor,
  });
}

