import 'package:hive/hive.dart';

part 'goal_model.g.dart'; // This file will be generated by build_runner

@HiveType(typeId: 1)
class Goal extends HiveObject {
  @HiveField(0)
  final String id;
  @HiveField(1)
  final String userId;
  @HiveField(2)
  final String name;
  @HiveField(3)
  final double targetAmount;
  @HiveField(4)
  double currentAmount;
  @HiveField(5)
  final DateTime? targetDate;

  Goal({
    required this.id,
    required this.userId,
    required this.name,
    required this.targetAmount,
    this.currentAmount = 0.0,
    this.targetDate,
  });
}

