// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCy3UtjgctvyPCJ9VwGcW81pCOqTrlRTBA',
    appId: '1:827890915131:web:be97f248db26a9e621891e',
    messagingSenderId: '827890915131',
    projectId: 'smart-expense-tracker-471d6',
    authDomain: 'smart-expense-tracker-471d6.firebaseapp.com',
    storageBucket: 'smart-expense-tracker-471d6.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAO9hKtDtnkth41erlsmRxxbnCkecl5nLo',
    appId: '1:827890915131:android:ccea551a5add74e921891e',
    messagingSenderId: '827890915131',
    projectId: 'smart-expense-tracker-471d6',
    storageBucket: 'smart-expense-tracker-471d6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCicoP-dzAF3xU9qhznD8BLhqwD87HcAzQ',
    appId: '1:827890915131:ios:a7874f0baf65687b21891e',
    messagingSenderId: '827890915131',
    projectId: 'smart-expense-tracker-471d6',
    storageBucket: 'smart-expense-tracker-471d6.firebasestorage.app',
    iosBundleId: 'com.example.smartExpenseTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCicoP-dzAF3xU9qhznD8BLhqwD87HcAzQ',
    appId: '1:827890915131:ios:a7874f0baf65687b21891e',
    messagingSenderId: '827890915131',
    projectId: 'smart-expense-tracker-471d6',
    storageBucket: 'smart-expense-tracker-471d6.firebasestorage.app',
    iosBundleId: 'com.example.smartExpenseTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCy3UtjgctvyPCJ9VwGcW81pCOqTrlRTBA',
    appId: '1:827890915131:web:7149d15ef95d56a421891e',
    messagingSenderId: '827890915131',
    projectId: 'smart-expense-tracker-471d6',
    authDomain: 'smart-expense-tracker-471d6.firebaseapp.com',
    storageBucket: 'smart-expense-tracker-471d6.firebasestorage.app',
  );
}
